version: '3'
services:
  rabbitpro:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1234"
    volumes:
      - "${DATA_PATH}:/Rabbit/data"
    image: ht944/rabbitpro:latest
    privileged: true
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

